version: '3'

services:
 wp:
  image: wordpress
  environment:
    - WORDPRESS_DB_HOST=db
    - WORDPRESS_DB_PASSWORD=${PASSWORD}
  volumes:
    - wp-data:/var/www/html
  ports:
    - 8080:80

 db:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=${PASSWORD}
  volumes:
    - db-data:/var/lib/mysql

volumes:
  db-data:
  wp-data:
