version: '3'

services:
  vote:
    build: ./vote
    depends_on:
      - redis
    ports:
      - 5000:80
    networks:
      - message-tier

  result:
    build: ./result
    depends_on:
      - db
    ports:
      - 5001:80
    networks:
      - database-tier

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - message-tier
      - database-tier

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - message-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database-tier

volumes:
  db-data:

networks:
  message-tier:
  database-tier:
