version: '3'

services:
  jenkins:
    build: .
    image: jenkins:custom
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:
